import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import "@/style/globals.css";
import "@/style/_fonts.css";
import "@/style/_colors.css";

export const metadata: Metadata = {
  title: "Kidoys",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full">
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
